<?if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	define("STATISTIC_SKIP_ACTIVITY_CHECK", "true");
	require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
}?>
<?$APPLICATION->IncludeComponent(
	"aspro:tabs.max", 
	"main", 
	array(
		"IBLOCK_TYPE" => "aspro_max_catalog",
		"IBLOCK_ID" => "55",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"TABS_CODE" => "HIT",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilterProp",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"PAGE_ELEMENT_COUNT" => "9",
		"LINE_ELEMENT_COUNT" => "5",
		"ADD_DETAIL_TO_SLIDER" => "Y",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "MINIMUM_PRICE",
			2 => "MAXIMUM_PRICE",
			3 => "HIT",
			4 => "BRAND",
			5 => "YM_ELEMENT_ID",
			6 => "EXPANDABLES_FILTER",
			7 => "LINK_SALE",
			8 => "IN_STOCK",
			9 => "EXTENDED_REVIEWS_COUNT",
			10 => "ASSOCIATED_FILTER",
			11 => "EXTENDED_REVIEWS_RAITING",
			12 => "PRODUCT_SET_GROUP",
			13 => "PRODUCT_SET",
			14 => "PRODUCT_SET_FILTER",
			15 => "BLOG_POST_ID",
			16 => "EXPANDABLES",
			17 => "CML2_ARTICLE",
			18 => "CML2_BASE_UNIT",
			19 => "BIG_BLOCK",
			20 => "LINK_VACANCY",
			21 => "VIDEO_YOUTUBE",
			22 => "POPUP_VIDEO",
			23 => "PROP_3555",
			24 => "PROP_2104",
			25 => "BLOG_COMMENTS_CNT",
			26 => "FORUM_MESSAGE_CNT",
			27 => "vote_count",
			28 => "PROP_3556",
			29 => "LINK_NEWS",
			30 => "PODBORKI",
			31 => "ASSOCIATED",
			32 => "HELP_TEXT",
			33 => "LINK_REGION",
			34 => "rating",
			35 => "CML2_TRAITS",
			36 => "LINK_STAFF",
			37 => "CML2_TAXES",
			38 => "LINK_BLOG",
			39 => "vote_sum",
			40 => "SALE_TEXT",
			41 => "FORUM_TOPIC_ID",
			42 => "PROP_2033",
			43 => "FAVORIT_ITEM",
			44 => "SERVICES",
			45 => "CML2_ATTRIBUTES",
			46 => "COLOR_REF2",
			47 => "PROP_2102",
			48 => "PROP_159",
			49 => "PROP_349",
			50 => "PROP_327",
			51 => "PROP_370",
			52 => "PROP_336",
			53 => "PROP_346",
			54 => "PROP_2120",
			55 => "PROP_2089",
			56 => "PROP_2103",
			57 => "PROP_2085",
			58 => "PROP_2083",
			59 => "PROP_348",
			60 => "PROP_350",
			61 => "PROP_2101",
			62 => "PROP_2067",
			63 => "PROP_319",
			64 => "PROP_328",
			65 => "PROP_338",
			66 => "PROP_2065",
			67 => "PROP_366",
			68 => "PROP_341",
			69 => "PROP_283",
			70 => "PROP_2066",
			71 => "PROP_342",
			72 => "PROP_367",
			73 => "PROP_2084",
			74 => "PROP_340",
			75 => "PROP_351",
			76 => "PROP_369",
			77 => "PROP_337",
			78 => "PROP_339",
			79 => "PROP_309",
			80 => "PROP_206",
			81 => "PROP_2100",
			82 => "PROP_315",
			83 => "PROP_2091",
			84 => "PROP_307",
			85 => "",
		),
		"OFFERS_LIMIT" => "0",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"BASKET_URL" => "/basket/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "N",
		"CACHE_FILTER" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"DISPLAY_COMPARE" => "Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "Y",
		"SHOW_ONE_CLICK_BUY" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_PROPERTIES" => array(
		),
		"USE_PRODUCT_QUANTITY" => "N",
		"CONVERT_CURRENCY" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "ajax",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"DISCOUNT_PRICE_CODE" => "",
		"AJAX_OPTION_ADDITIONAL" => "",
		"SHOW_ADD_FAVORITES" => "Y",
		"SHOW_ARTICLE_SKU" => "Y",
		"SECTION_NAME_FILTER" => "",
		"SECTION_SLIDER_FILTER" => "21",
		"COMPONENT_TEMPLATE" => "main",
		"OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "ARTICLE",
			1 => "SIZES",
			2 => "AGE",
			3 => "",
		),
		"OFFER_TREE_PROPS" => array(
			0 => "SIZES",
			1 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"SHOW_MEASURE" => "Y",
		"OFFERS_CART_PROPERTIES" => array(
		),
		"DISPLAY_WISH_BUTTONS" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_RATING" => "Y",
		"MAX_GALLERY_ITEMS" => "5",
		"SHOW_GALLERY" => "Y",
		"SHOW_PROPS" => "Y",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
		"SALE_STIKER" => "SALE_TEXT",
		"FAV_ITEM" => "FAVORIT_ITEM",
		"SHOW_DISCOUNT_TIME" => "Y",
		"STORES" => array(
			0 => "1",
			1 => "",
		),
		"STIKERS_PROP" => "HIT",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "Y",
		"SHOW_MEASURE_WITH_RATIO" => "Y",
		"SHOW_DISCOUNT_TIME_EACH_SKU" => "Y",
		"TITLE_BLOCK" => "Лучшие предложения",
		"TITLE_BLOCK_ALL" => "Весь каталог",
		"ALL_URL" => "catalog/",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"ID_FOR_TABS" => "Y",
		"ADD_PICT_PROP_OFFER" => "MORE_PHOTO",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "",
			1 => "",
		)
	),
	false
);?>